const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const mockProducts = [
  {
    title: 'Matematik Konu Anlatımı',
    slug: 'matematik-konu-anlatimi',
    price: 149.90,
    discountedPrice: 99.90,
    coverImage: '/covers/matematik.png',
    type: 'Dijital Kitap',
    description: 'Sıfırdan ileri seviyeye kadar tüm matematik konularını kapsayan, görsellerle zenrichleştirilmiş dijital kitap. Her bölüm sonunda çözümlü sorular ve pratik testler içerir. 450+ sayfa, interaktif PDF formatında.',
    isFeatured: true,
    isBestseller: true,
    contents: [
      'Sayılar ve İşlemler (45 sayfa)',
      'Cebir ve Denklemler (62 sayfa)',
      'Geometri Temelleri (58 sayfa)',
      'Trigonometri (44 sayfa)',
      'Analitik Geometri (52 sayfa)',
      'Limit ve Türev (48 sayfa)',
      'İntegral (42 sayfa)',
      'Olasılık ve İstatistik (35 sayfa)',
      '500+ Çözümlü Soru',
      '10 Deneme Sınavı',
    ],
    outcomes: ['Matematik konularında tam hakimiyet', 'Netlerinizi artıracak pratikler', 'Sınav formatına uyum'],
  },
  {
    title: 'Türkçe Dil Bilgisi Rehberi',
    slug: 'turkce-dil-bilgisi',
    price: 129.90,
    discountedPrice: null,
    coverImage: '/covers/turkce.png',
    type: 'Dijital Kitap',
    description: 'Ses bilgisinden cümle analizine kadar Türk dili kurallarını öğreten, edebiyat akımlarını ve dönemlerini detaylıca inceleyen kapsamlı dijital kitap. Güncel sınav formatına uygun hazırlanmıştır.',
    isFeatured: true,
    isBestseller: false,
    contents: [
      'Ses Bilgisi (32 sayfa)',
      'Yapı Bilgisi (45 sayfa)',
      'Sözcük Türleri (68 sayfa)',
      'Cümle Bilgisi (55 sayfa)',
      'Anlatım Bozuklukları (28 sayfa)',
      'Paragraf ve Anlam (42 sayfa)',
      'Edebiyat Tarihi (58 sayfa)',
      'Edebi Türler (32 sayfa)',
      '400+ Çözümlü Soru',
    ],
    outcomes: ['Dil bilgisi kurallarını eksiksiz öğrenme', 'Paragraf sorularında hız kazanma', 'Edebiyat konularında başarı'],
  },
  {
    title: 'Fen Bilimleri Ansiklopedik Kitap',
    slug: 'fen-bilimleri-kitabi',
    price: 179.90,
    discountedPrice: 139.90,
    coverImage: '/covers/fen.png',
    type: 'Dijital Kitap',
    description: 'Fizik, Kimya ve Biyoloji derslerini tek bir kaynakta birleştiren, deneylerle ve görsellerle desteklenmiş kapsamlı dijital eğitim kitabı. Her konu sonunda mini testler ve değerlendirme soruları içerir.',
    isFeatured: false,
    isBestseller: false,
    contents: [
      'Fizik: Mekanik (65 sayfa)',
      'Fizik: Elektrik ve Manyetizma (55 sayfa)',
      'Fizik: Dalgalar ve Optik (40 sayfa)',
      'Kimya: Atom ve Periyodik Tablo (48 sayfa)',
      'Kimya: Kimyasal Tepkimeler (52 sayfa)',
      'Biyoloji: Hücre ve Canlılar (60 sayfa)',
      'Biyoloji: Genetik ve Evrim (45 sayfa)',
      'Laboratuvar Deneyleri (35 sayfa)',
      '600+ Çözümlü Soru',
    ],
    outcomes: ['Fizik, Kimya ve Biyoloji temelleri', 'Görsel deney anlatımları', 'Kapsamlı fen soru havuzu'],
  },
  {
    title: 'Tarih Kronolojik Rehber',
    slug: 'tarih-kronolojik-rehber',
    price: 119.90,
    discountedPrice: null,
    coverImage: '/covers/tarih.png',
    type: 'Dijital Kitap',
    description: 'Dünya ve Türk tarihini kronolojik sırayla ele alan, haritalar ve infografiklerle zenginleştirilmiş kapsamlı tarih kitap. İnkılap tarihi ve çağdaş dünya tarihi bölümleri güncel müfredata uygun hazırlanmıştır.',
    isFeatured: false,
    isBestseller: false,
    contents: [
      'İlk Çağ Uygarlıkları (35 sayfa)',
      'İslam Tarihi (40 sayfa)',
      'Türk-İslam Devletleri (48 sayfa)',
      'Osmanlı Devleti: Kuruluş-Yükseliş (55 sayfa)',
      'Osmanlı Devleti: Duraklama-Çöküş (45 sayfa)',
      'Kurtuluş Savaşı (52 sayfa)',
      'Atatürk İlkeleri ve İnkılapları (42 sayfa)',
      'Çağdaş Dünya Tarihi (38 sayfa)',
      '350+ Çözümlü Soru',
    ],
    outcomes: ['Tarihsel kronolojiye hakimiyet', 'Harita ve görsel analizler', 'Sınav odaklı tarih bilgisi'],
  },
  {
    title: 'Matematik Video Ders Seti',
    slug: 'matematik-video-seti',
    price: 349.90,
    discountedPrice: 249.90,
    coverImage: '/covers/matematik.png',
    type: 'Video Ders Seti',
    description: 'Alanında uzman eğitmenler tarafından hazırlanan, sıfırdan ileri seviyeye kadar tüm matematik konularını kapsayan HD video ders seti. Her ders sonunda interaktif quizler ve ödevler içerir.',
    isFeatured: true,
    isBestseller: true,
    contents: [
      'Temel Matematik (22 video, 18 saat)',
      'Cebir ve Denklemler (28 video, 20 saat)',
      'Geometri (32 video, 24 saat)',
      'Trigonometri (18 video, 14 saat)',
      'Analitik Geometri (22 video, 16 saat)',
      'Limit ve Süreklilik (16 video, 10 saat)',
      'Türev (24 video, 12 saat)',
      'İntegral (14 video, 6 saat)',
      'Olasılık (10 video, 4 saat)',
      '186 Quiz ve Ödev',
    ],
    outcomes: ['120+ saat konu anlatımı', 'Detaylı soru çözümleri', 'Pratik quiz ve ödevler'],
  },
  {
    title: 'Fen Bilimleri Video Seti',
    slug: 'fen-bilimleri-video-seti',
    price: 299.90,
    discountedPrice: 219.90,
    coverImage: '/covers/fen.png',
    type: 'Video Ders Seti',
    description: 'Fizik, Kimya ve Biyoloji derslerini tek bir sette birleştiren profesyonel video ders paketi. Animasyonlar ve 3D modeller ile desteklenmiş, görsel öğrenmeye odaklı interaktif dersler.',
    isFeatured: true,
    isBestseller: false,
    contents: [
      'Fizik: Mekanik (24 video, 18 saat)',
      'Fizik: Elektrik (20 video, 14 saat)',
      'Fizik: Dalgalar ve Optik (16 video, 10 saat)',
      'Kimya: Temel Kavramlar (22 video, 16 saat)',
      'Kimya: Organik Kimya (14 video, 8 saat)',
      'Biyoloji: Hücre ve Genetik (28 video, 18 saat)',
      'Biyoloji: Ekosistem (12 video, 6 saat)',
      'Deney Videoları (12 video, 6 saat)',
      '148 Konu Testi',
    ],
    outcomes: ['3D animasyonlu görsel anlatım', 'Ders notları ve çalışma dokümanları', 'Sınavda çıkabilecek soru tipleri'],
  },
  {
    title: 'İngilizce Kapsamlı Video Kursu',
    slug: 'ingilizce-video-kursu',
    price: 279.90,
    discountedPrice: null,
    coverImage: '/covers/ingilizce.png',
    type: 'Video Ders Seti',
    description: 'Başlangıçtan ileri seviyeye kadar İngilizce öğretim seti. Native speaker eğitmenlerle pratik konuşma, gramer, kelime hazinesi ve sınav hazırlığı videoları. Altyazılı ve interaktif.',
    isFeatured: false,
    isBestseller: false,
    contents: [
      'A1-A2: Temel İngilizce (30 video, 20 saat)',
      'B1: Orta Seviye (25 video, 18 saat)',
      'B2: Üst Orta (25 video, 18 saat)',
      'C1: İleri Seviye (20 video, 14 saat)',
      'Konuşma Pratikleri (10 video, 5 saat)',
      'YDS/YÖKDİL Hazırlık (10 video, 5 saat)',
      '1000+ Kelime Kartı',
      '120 Gramer Alıştırması',
    ],
    outcomes: ['A1-C1 arası tüm seviyeler', 'Akıcı İngilizce konuşma becerisi', 'Sınavlara hazırlık ve pratikler'],
  },
  {
    title: 'TYT Deneme Sınavı Paketi',
    slug: 'tyt-deneme-paketi',
    price: 199.90,
    discountedPrice: 149.90,
    coverImage: '/covers/deneme.png',
    type: 'Deneme Paketi',
    description: 'ÖSYM formatına birebir uygun, 30 adet kapsamlı TYT deneme sınavı. Otomatik puanlama, detaylı analiz raporu ve konu bazlı performans takibi. Her deneme 120 sorudan oluşur.',
    isFeatured: true,
    isBestseller: true,
    contents: [
      '30 Tam Deneme Sınavı (120 soru/deneme)',
      'Toplam 3.600 Soru',
      'Otomatik Puanlama Sistemi',
      'Detaylı Çözüm Videoları',
      'Konu Bazlı Performans Analizi',
      'Türkiye Geneli Sıralama',
      'Net Takip Grafiği',
      'Zayıf Konu Önerileri',
    ],
    outcomes: ['30 adet online TYT denemesi', 'Detaylı video çözümler', 'Konu bazlı başarı grafikleri'],
  },
  {
    title: 'AYT Deneme Sınavı Paketi',
    slug: 'ayt-deneme-paketi',
    price: 229.90,
    discountedPrice: 179.90,
    coverImage: '/covers/deneme.png',
    type: 'Deneme Paketi',
    description: 'AYT sınavına özel, alan bazlı deneme sınavları. Sayısal, Sözel ve Eşit Ağırlık alanları için ayrı deneme setleri. Detaylı analizler ve çözüm videoları dahil.',
    isFeatured: false,
    isBestseller: false,
    contents: [
      '10 Sayısal AYT Denemesi',
      '8 Sözel AYT Denemesi',
      '7 Eşit Ağırlık AYT Denemesi',
      'Toplam 4.000 Soru',
      'Otomatik Puanlama ve Net Hesaplama',
      'Konu Bazlı Analiz Raporu',
      'Video Çözümler',
      'Sıralama ve Karşılaştırma',
    ],
    outcomes: ['Alan bazlı denemeler', 'Hassas net hesaplamaları', 'Sıralama raporları'],
  },
  {
    title: 'Matematik Ultimate Kombo',
    slug: 'matematik-ultimate-kombo',
    price: 699.70,
    discountedPrice: 399.90,
    coverImage: '/covers/kombo.png',
    type: 'Kombo Paket',
    description: 'Matematik başarısı için ihtiyacınız olan her şey tek pakette! Dijital kitap, video ders seti ve deneme sınavları bir arada. Ayrı ayrı almaya göre %40 avantajlı.',
    isFeatured: true,
    isBestseller: true,
    contents: [
      '📚 Matematik Konu Anlatımı Kitabı (456 sayfa)',
      '🎬 Matematik Video Ders Seti (124 saat, 186 video)',
      '📝 30 Matematik Deneme Sınavı',
      '✅ 500+ Çözümlü Soru',
      '✅ Konu Bazlı Performans Analizi',
      '✅ Ömür Boyu Erişim',
      '🎁 Bonus: Formül Kartları PDF',
      '🎁 Bonus: Soru Çözüm Maratonu (10 saat)',
    ],
    outcomes: ['Tüm matematik kaynakları tek pakette', 'Yüksek indirim avantajı', 'Bonus içerikler ve soru maratonları'],
  },
];

async function main() {
  console.log('Seeding products...');
  for (const prod of mockProducts) {
    await prisma.product.upsert({
      where: { slug: prod.slug },
      update: {},
      create: prod,
    });
  }
  console.log('Products seeded successfully.');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
